server:
  port: 8080

spring:
  application:
    name: Banking Service

logging:
  level:
    com.skypay.banking: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"